### ISSUE TITLE
网址打不开

### ISSUE THREAD

**Issue by RobKing9** [VERGESSE/pixiv-golang#1]
你好 你的博客网址打不开了

**Comment by VERGESSE** [comment]
已经修复




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "VERGESSE/pixiv-golang"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月9日(星期四) 晚上8:05
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[VERGESSE/pixiv-golang] 网址打不开 (Issue #1)





 
你好 你的博客网址打不开了
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
